/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface;

import business.role.Citizen;
import business.role.EmergencyOperationCoordinator;
import business.role.HospitalManager;
import business.role.VolunteerCoordinator;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author abhis
 */
public class CitizenJPanel extends javax.swing.JPanel {
    String newsflashtext;
    Citizen volunteer;
    /**
     * Creates new form CitizenJPanel
     */
    public CitizenJPanel(Citizen citizen) {
        initComponents();
        populateAlert();
        this.volunteer = citizen;
        
    }
    
    public void populateAlert(){
        EmergencyOperationCoordinator emergencycoordinator = EmergencyOperationCoordinator.findCoordinator(3);
        newsflashtext = emergencycoordinator.getAlert();
        txtNewsFlash.setText(newsflashtext);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNewsFlash = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnVolunteerSignup = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 1000));

        txtNewsFlash.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        txtNewsFlash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewsFlashActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel1.setText("Disaster Alerts");

        btnVolunteerSignup.setBackground(new java.awt.Color(0, 0, 153));
        btnVolunteerSignup.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btnVolunteerSignup.setForeground(new java.awt.Color(255, 255, 255));
        btnVolunteerSignup.setText("Register As a Volunteer");
        btnVolunteerSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolunteerSignupActionPerformed(evt);
            }
        });

        btnHelp.setBackground(new java.awt.Color(0, 0, 153));
        btnHelp.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btnHelp.setForeground(new java.awt.Color(255, 255, 255));
        btnHelp.setText("Register As a Patient");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolunteerSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnHelp))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewsFlash, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewsFlash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolunteerSignup)
                    .addComponent(btnHelp))
                .addContainerGap(617, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewsFlashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewsFlashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewsFlashActionPerformed

    private void btnVolunteerSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolunteerSignupActionPerformed
        // TODO add your handling code here:
        VolunteerCoordinator coordinator =VolunteerCoordinator.findCoordinator(1);
        
        if (coordinator != null) {
  

        coordinator.addVolunteer(volunteer);
        System.out.println("New volunteer signed up: " + volunteer.getName());

        JOptionPane.showMessageDialog(this, "Volunteer signed up successfully!");
    } else {
        System.err.println("Coordinator not found!");
        JOptionPane.showMessageDialog(this, "Error: Coordinator not found!");
    }
        

    }//GEN-LAST:event_btnVolunteerSignupActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:
        HospitalManager manager = HospitalManager.findManager(5);
        
        if (manager != null) {
  

        manager.addPatient(volunteer);
        System.out.println("Patient Registered " + volunteer.getName());

        JOptionPane.showMessageDialog(this, "Patient signed up successfully!");
    } else {
        System.err.println("Manager not found!");
       JOptionPane.showMessageDialog(this, "Error: Manager not found!");
    }
        
        
    }//GEN-LAST:event_btnHelpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnVolunteerSignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNewsFlash;
    // End of variables declaration//GEN-END:variables


}
