/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface;

import business.role.DamageAnalyst;
import business.role.FieldResponseCoordinator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abhis
 */
public class DamageAnalystJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DamageAnalystJPanel
     */
    public DamageAnalystJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCalamity = new javax.swing.JTextField();
        lblCalamity = new javax.swing.JLabel();
        lblDamage = new javax.swing.JLabel();
        txtDamage = new javax.swing.JTextField();
        btnSendReport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLog = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 1000));

        txtCalamity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalamityActionPerformed(evt);
            }
        });

        lblCalamity.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        lblCalamity.setText("Calamity");

        lblDamage.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        lblDamage.setText("Damages in $ : ");

        txtDamage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDamageActionPerformed(evt);
            }
        });

        btnSendReport.setBackground(new java.awt.Color(0, 0, 153));
        btnSendReport.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btnSendReport.setForeground(new java.awt.Color(255, 255, 255));
        btnSendReport.setText("Send Current Report");
        btnSendReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendReportActionPerformed(evt);
            }
        });

        tblLog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Calamity", "Damages in $:", "Area"
            }
        ));
        jScrollPane1.setViewportView(tblLog);

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Log Entry");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel1.setText("Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSendReport, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jButton1)))
                        .addGap(0, 368, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDamage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCalamity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCalamity, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCalamity)
                    .addComponent(txtCalamity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDamage)
                    .addComponent(txtDamage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSendReport)
                    .addComponent(jButton1))
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(418, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCalamityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalamityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalamityActionPerformed

    private void txtDamageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDamageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDamageActionPerformed

    private void btnSendReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendReportActionPerformed

        DamageAnalyst analyst = DamageAnalyst.findDamageAnalyst(2);

        FieldResponseCoordinator coordinator = FieldResponseCoordinator.findCoordinator(4);

        String calamityType = txtCalamity.getText();
        String area =  txtArea.getText();
        double damageExtent;
        try {
            damageExtent = Double.parseDouble(txtDamage.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number for Damage Extent",
                    "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        analyst.sendDamageReport(coordinator, calamityType, damageExtent, area);

        JOptionPane.showMessageDialog(this, "Damage report sent to " + coordinator.getName() + "(Field Response Coordinator",
                "Report Sent", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSendReportActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        populateLogs();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendReport;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCalamity;
    private javax.swing.JLabel lblDamage;
    private javax.swing.JTable tblLog;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtCalamity;
    private javax.swing.JTextField txtDamage;
    // End of variables declaration//GEN-END:variables


    
   private void populateLogs() {
    // Get the table model
    DefaultTableModel model = (DefaultTableModel) tblLog.getModel();

    // Check if any text field is empty before adding the row
    if (txtCalamity.getText().isEmpty() || txtDamage.getText().isEmpty() || txtArea.getText().isEmpty()) {
        return;  // Skip adding if any text field is empty
    }

    // Add a new row for each log entry
    Object row[] = new Object[3];
    row[0] = txtCalamity.getText();  // Get calamity description
    row[1] = txtDamage.getText();    // Get damage description
    row[2] = txtArea.getText();      // Get area description

    // Add the row to the table model
    model.addRow(row);

    // Optionally, clear the text fields after adding the log
    txtCalamity.setText("");
    txtDamage.setText("");
    txtArea.setText("");
}


}
