/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface;

import business.role.EmergencyOperationCoordinator;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abhis
 */
public class EmergencyOperationCoordinatorJPanel extends javax.swing.JPanel {
    /**
     * Creates new form EmergencyOperationCoordinatorJPanel
     */
    public EmergencyOperationCoordinatorJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbDisaster = new javax.swing.JComboBox<>();
        txtLocation = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSeverity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmergency = new javax.swing.JTable();
        btnTrigger = new javax.swing.JButton();
        btnStopTrigger = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 750));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel1.setText("Select Disaster Type:");

        cmbDisaster.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Earthquake" ,"Flood", "Fire", "Tornado"}));
        cmbDisaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDisasterActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel2.setText("Location");

        txtSeverity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeverityActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel3.setText("Severity");

        tblEmergency.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        tblEmergency.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Area", "Status", "Population Affected", "Severity"
            }
        ));
        jScrollPane1.setViewportView(tblEmergency);

        btnTrigger.setBackground(new java.awt.Color(0, 0, 153));
        btnTrigger.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btnTrigger.setForeground(new java.awt.Color(255, 255, 255));
        btnTrigger.setText("Trigger Alert");
        btnTrigger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTriggerActionPerformed(evt);
            }
        });

        btnStopTrigger.setBackground(new java.awt.Color(0, 0, 153));
        btnStopTrigger.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btnStopTrigger.setForeground(new java.awt.Color(255, 255, 255));
        btnStopTrigger.setText("Stop Alert");
        btnStopTrigger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopTriggerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnTrigger)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStopTrigger))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSeverity, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cmbDisaster, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSeverity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbDisaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(114, 114, 114)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrigger)
                    .addComponent(btnStopTrigger))
                .addContainerGap(544, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSeverityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeverityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeverityActionPerformed

    private void cmbDisasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDisasterActionPerformed
        // TODO add your handling code here:
            String selectedDisaster = (String) cmbDisaster.getSelectedItem();
            displayDisasterDetails(selectedDisaster);
    }//GEN-LAST:event_cmbDisasterActionPerformed

    private void btnTriggerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTriggerActionPerformed
        // TODO add your handling code here:
         triggerDisasterAlert();
    }//GEN-LAST:event_btnTriggerActionPerformed

    private void btnStopTriggerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopTriggerActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Alerts Retracted");
        EmergencyOperationCoordinator emergencycoordinator = EmergencyOperationCoordinator.findCoordinator(3);
        emergencycoordinator.setAlert("You are Safe.");
    }//GEN-LAST:event_btnStopTriggerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStopTrigger;
    private javax.swing.JButton btnTrigger;
    private javax.swing.JComboBox<String> cmbDisaster;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmergency;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtSeverity;
    // End of variables declaration//GEN-END:variables

    private void displayDisasterDetails(String disasterType) {
        switch (disasterType) {
            case "Earthquake":
                txtLocation.setText("San Francisco, CA");
                txtSeverity.setText("7.5 magnitude");
                break;
            case "Flood":
                txtLocation.setText("New Orleans, LA");
                txtSeverity.setText("Severe flooding");
                break;
            case "Fire":
                txtLocation.setText("California");
                txtSeverity.setText("Wildfire alert");
                break;
            case "Tornado":
                txtLocation.setText("Kansas, US");
                txtSeverity.setText("Category 5");
                break;
        }
    }

    private void triggerDisasterAlert() {
        String disasterType = (String) cmbDisaster.getSelectedItem();
        String location = txtLocation.getText();
        String severity = txtSeverity.getText();

        // Update the table with affected areas
        updateAffectedAreas(disasterType, location);

        // Log the disaster alert
        System.out.println("Disaster Alert Triggered!");
        
        EmergencyOperationCoordinator emergencycoordinator = EmergencyOperationCoordinator.findCoordinator(3);
        emergencycoordinator.setAlert( severity + disasterType +" occured in "+ location+" .Seek shelter and help");

        JOptionPane.showMessageDialog(null,"News Flash sent to all the Citizens");
        
        
    }

    private void updateAffectedAreas(String disasterType, String location) {
        DefaultTableModel model = (DefaultTableModel) tblEmergency.getModel();
        model.setRowCount(0);  // Clear previous data

        // Example of adding affected areas to the table
        model.addRow(new Object[] { "Area 1", "Evacuating", "500", "High" });
        model.addRow(new Object[] { "Area 2", "Alerted", "300", "Medium" });
        model.addRow(new Object[] { "Area 3", "Safe", "150", "Low" });
    }

}
