/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface;

import business.role.FieldResponseCoordinator;
import business.role.ResourceSpecialist;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abhis
 */
public class FieldResponseCoordinatorJPanel extends javax.swing.JPanel {
    FieldResponseCoordinator coordinator = FieldResponseCoordinator.findCoordinator(4);
    ResourceSpecialist specialist = ResourceSpecialist.findSpecialist(7);
    /**
     * Creates new form FieldResponseCoordinatorJPanel
     */
    public FieldResponseCoordinatorJPanel() {
        initComponents();
        populateDamageTable();
        populateFunds();
        populateAllocateFunds();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDamageReport = new javax.swing.JTable();
        lblFunds = new javax.swing.JLabel();
        txtFunds = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAllocateFunds = new javax.swing.JTable();
        btnSendFunds = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 1000));

        tblDamageReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Damage Report", "Damage Value"
            }
        ));
        jScrollPane1.setViewportView(tblDamageReport);

        lblFunds.setText("Available Funds");

        txtFunds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFundsActionPerformed(evt);
            }
        });

        tblAllocateFunds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Aid Request By", "Items", "Value"
            }
        ));
        jScrollPane2.setViewportView(tblAllocateFunds);

        btnSendFunds.setText("Send Funds");
        btnSendFunds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendFundsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFunds)
                                .addGap(15, 15, 15)
                                .addComponent(txtFunds, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSendFunds, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFunds)
                    .addComponent(txtFunds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnSendFunds)
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFundsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFundsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFundsActionPerformed

    private void btnSendFundsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendFundsActionPerformed
        // TODO add your handling code here:
        double newValue = coordinator.getFunds() - coordinator.getFundsNeeded();
        txtFunds.setText(String.valueOf(newValue));
        specialist.fundsApprovedBy(coordinator, coordinator.getFundsNeeded(), true);
    }//GEN-LAST:event_btnSendFundsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendFunds;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFunds;
    private javax.swing.JTable tblAllocateFunds;
    private javax.swing.JTable tblDamageReport;
    private javax.swing.JTextField txtFunds;
    // End of variables declaration//GEN-END:variables

    private void populateDamageTable() {

        DefaultTableModel model = (DefaultTableModel) tblDamageReport.getModel();
        model.setRowCount(0);

        if (coordinator != null && coordinator.getLatestCalamity() != null) {
            Object row[] = new Object[3];
            row[0] = coordinator.getLatestCalamity();
            row[1] = coordinator.getLatestDamageExtent();
            row[2] = coordinator.getArea();
            model.addRow(row);
        } else {
            System.out.println("No damage report available to populate the table.");
        }
    }

    private void populateFunds() {
        coordinator.setFunds(1000000.0);
        double funds = coordinator.getFunds();
        txtFunds.setText(String.valueOf(funds));
    }

    private void populateAllocateFunds() {
        DefaultTableModel model = (DefaultTableModel) tblAllocateFunds.getModel();
        model.setRowCount(0);
        
        if (coordinator != null && coordinator.getItems()!= null) {
            Object row[] = new Object[3];
            row[0] = coordinator.getRequestMadeBy();
            row[1] = coordinator.getItems();
            row[2] = coordinator.getFundsNeeded();
            model.addRow(row);
        } else {
            System.out.println("No Fund Request Made");
        }
        
    }

}
