/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface;

import business.role.Citizen;
import business.role.HospitalManager;
import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author meera
 */
public class HospitalManagerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalManagerJPanel
     */
    public HospitalManagerJPanel() {
        initComponents();
        populatePatientTable();
        populateHospitalCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatient = new javax.swing.JTable();
        btnAdmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbHospital = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAdmit = new javax.swing.JTable();

        tblPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "ID", "Area", "Nationality"
            }
        ));
        jScrollPane1.setViewportView(tblPatient);

        btnAdmit.setText("Admit");
        btnAdmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmitActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Hospital ");

        cmbHospital.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4", "Item5"}));

        tblAdmit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Hospital"
            }
        ));
        jScrollPane2.setViewportView(tblAdmit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdmit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(cmbHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cmbHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnAdmit)
                .addGap(51, 51, 51)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmitActionPerformed
        // TODO add your handling code here:
        int selectedPatientRow = tblPatient.getSelectedRow();
        String selectedHospital = (String) cmbHospital.getSelectedItem();

        if (selectedPatientRow >= 0 && selectedHospital != null) {
            DefaultTableModel patientModel = (DefaultTableModel) tblPatient.getModel();
            String patientName = (String) patientModel.getValueAt(selectedPatientRow, 0);

            DefaultTableModel admitModel = (DefaultTableModel) tblAdmit.getModel();
            admitModel.addRow(new Object[]{patientName, selectedHospital});

            // Optional: Log or notify admission
            System.out.println("Admitted " + patientName + " to " + selectedHospital);
        } else {
            System.out.println("Please select a patient and a hospital.");
        }
    }//GEN-LAST:event_btnAdmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmit;
    private javax.swing.JComboBox<String> cmbHospital;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAdmit;
    private javax.swing.JTable tblPatient;
    // End of variables declaration//GEN-END:variables
    private void populatePatientTable() {
        DefaultTableModel model = (DefaultTableModel) tblPatient.getModel();
        model.setRowCount(0); // Clear the table

        for (HospitalManager manager : HospitalManager.getAllManagers()) {
            for (Citizen patient : manager.getAllPatients()) {
                model.addRow(new Object[]{patient.getName(), patient.getCitizenId(), patient.getAddress(), patient.getNationality()});
            }
        }
    }

    private void populateHospitalCombo() {
    cmbHospital.removeAllItems(); // Clear existing items

    String[] hospitalNames = {
        "City General Hospital",
        "Sunrise Medical Center",
        "Harmony Health Clinic",
        "Green Valley Hospital",
        "Oceanview Medical Facility"
    };

    for (String hospitalName : hospitalNames) {
        cmbHospital.addItem(hospitalName);
    }
}


}
