/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface;

import business.role.ResponseTeamAgent;
import business.role.ResponseTeamCoordinator;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abhis
 */
public class ResponseTeamAgentJPanel extends javax.swing.JPanel {

    private ArrayList<ResponseTeamAgent> teamAgents;

    /**
     * Creates new form ResponseTeamAgentPanel
     * @param agent
     */
    public ResponseTeamAgentJPanel(ArrayList<ResponseTeamAgent> teamAgents) {
        initComponents();
        populateAgentsCombo();
        this.teamAgents = teamAgents;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgent = new javax.swing.JTable();
        cmbAgent = new javax.swing.JComboBox<>();

        tblAgent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Task", "Area"
            }
        ));
        jScrollPane1.setViewportView(tblAgent);

        cmbAgent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAgentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(cmbAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAgentActionPerformed
        // TODO add your handling code here:
        String selectedAgentName = (String) cmbAgent.getSelectedItem();

        if (selectedAgentName != null) {
 
            for (ResponseTeamAgent agent : teamAgents) {
                if (agent.getName().equals(selectedAgentName)) {
   
                    DefaultTableModel model = (DefaultTableModel) tblAgent.getModel();
                    model.setRowCount(0); 
                    model.addRow(new Object[]{agent.getAssignedTask(), agent.getAssignedArea()});
                    break;
                }
            }
        }
    }//GEN-LAST:event_cmbAgentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbAgent;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAgent;
    // End of variables declaration//GEN-END:variables
    private void populateAgentsCombo() {
        cmbAgent.removeAllItems();
        for(ResponseTeamAgent agent : teamAgents){
            cmbAgent.addItem(agent.getName());
        }
    }

}
