/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface;

import business.enterprise.Enterprise;
import business.organization.Organization;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abhis
 */
public class SystemAdminJPanel extends javax.swing.JPanel {

    private ArrayList<Enterprise> enterprises = new ArrayList<>();
    private DefaultTableModel enterpriseTableModel;
    private DefaultTableModel organizationTableModel;

    /**
     * Creates new form SystemAdminJPanel
     */
    public SystemAdminJPanel() {
        initComponents();
        initializeTables();
        initializeComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddEnterprise = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnterprise = new javax.swing.JTable();
        btnDeleteEnterprise = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrganizations = new javax.swing.JTable();
        cmbEnterprises = new javax.swing.JComboBox<>();
        btnAddOrg = new javax.swing.JButton();
        btnDeleteOrg = new javax.swing.JButton();
        txtEnterprise = new javax.swing.JTextField();
        txtOrganizations = new javax.swing.JTextField();

        btnAddEnterprise.setText("Add");
        btnAddEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEnterpriseActionPerformed(evt);
            }
        });

        tblEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise"
            }
        ));
        jScrollPane1.setViewportView(tblEnterprise);

        btnDeleteEnterprise.setText("Delete");
        btnDeleteEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEnterpriseActionPerformed(evt);
            }
        });

        tblOrganizations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organizations"
            }
        ));
        jScrollPane2.setViewportView(tblOrganizations);

        cmbEnterprises.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEnterprises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEnterprisesActionPerformed(evt);
            }
        });

        btnAddOrg.setText("Add");
        btnAddOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrgActionPerformed(evt);
            }
        });

        btnDeleteOrg.setText("Delete");
        btnDeleteOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOrgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbEnterprises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAddEnterprise)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteEnterprise))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAddOrg)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtOrganizations, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteOrg))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(289, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddEnterprise)
                    .addComponent(btnDeleteEnterprise)
                    .addComponent(txtEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(cmbEnterprises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddOrg)
                    .addComponent(btnDeleteOrg)
                    .addComponent(txtOrganizations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEnterpriseActionPerformed
        // TODO add your handling code here:
        String enterpriseName = txtEnterprise.getText().trim();
        if (!enterpriseName.isEmpty()) {
            Enterprise enterprise = new Enterprise(enterpriseName);
            enterprises.add(enterprise);
            initializeComboBox();
            updateEnterpriseTable();
            txtEnterprise.setText(""); // Clear input field
        } else {
            JOptionPane.showMessageDialog(this, "Enterprise name cannot be empty.");
        }
    }//GEN-LAST:event_btnAddEnterpriseActionPerformed

    private void btnDeleteEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEnterpriseActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblEnterprise.getSelectedRow();
        if (selectedRow >= 0) {
            enterprises.remove(selectedRow);
            initializeComboBox();
            updateEnterpriseTable();
        } else {
            JOptionPane.showMessageDialog(this, "Please select an enterprise to delete.");
        }
    }//GEN-LAST:event_btnDeleteEnterpriseActionPerformed

    private void cmbEnterprisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEnterprisesActionPerformed
        // TODO add your handling code here:
        int selectedIndex = cmbEnterprises.getSelectedIndex();
        if (selectedIndex >= 0) {
            Enterprise selectedEnterprise = enterprises.get(selectedIndex);
            updateOrganizationTable(selectedEnterprise);
    }
    }//GEN-LAST:event_cmbEnterprisesActionPerformed

    private void btnAddOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrgActionPerformed
        // TODO add your handling code here:
        int selectedIndex = cmbEnterprises.getSelectedIndex();
        if (selectedIndex >= 0) {
            Enterprise selectedEnterprise = enterprises.get(selectedIndex);
            String orgName = txtOrganizations.getText().trim();
            if (!orgName.isEmpty()) {
                Organization newOrg = new Organization(selectedEnterprise.getOrglist().size() + 1, orgName, "", "", "", "");
                selectedEnterprise.addOrg(newOrg);
                updateOrganizationTable(selectedEnterprise);
                txtOrganizations.setText(""); // Clear input field
            } else {
                JOptionPane.showMessageDialog(this, "Organization name cannot be empty.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select an enterprise.");
        }
    }//GEN-LAST:event_btnAddOrgActionPerformed

    private void btnDeleteOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOrgActionPerformed
        // TODO add your handling code here:
        int selectedIndex = cmbEnterprises.getSelectedIndex();
        int selectedRow = tblOrganizations.getSelectedRow();
        if (selectedIndex >= 0 && selectedRow >= 0) {
            Enterprise selectedEnterprise = enterprises.get(selectedIndex);
            selectedEnterprise.getOrglist().remove(selectedRow);
            updateOrganizationTable(selectedEnterprise);
        } else {
            JOptionPane.showMessageDialog(this, "Please select an enterprise and an organization.");
        }
    }//GEN-LAST:event_btnDeleteOrgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEnterprise;
    private javax.swing.JButton btnAddOrg;
    private javax.swing.JButton btnDeleteEnterprise;
    private javax.swing.JButton btnDeleteOrg;
    private javax.swing.JComboBox<String> cmbEnterprises;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblEnterprise;
    private javax.swing.JTable tblOrganizations;
    private javax.swing.JTextField txtEnterprise;
    private javax.swing.JTextField txtOrganizations;
    // End of variables declaration//GEN-END:variables

    private void initializeTables() {
        enterpriseTableModel = (DefaultTableModel) tblEnterprise.getModel();
        organizationTableModel = (DefaultTableModel) tblOrganizations.getModel();
        
        updateEnterpriseTable();
    }

    private void initializeComboBox() {
        cmbEnterprises.removeAllItems();
        for (Enterprise enterprise : enterprises) {
            cmbEnterprises.addItem(enterprise.getType());
        }
    }

    private void updateEnterpriseTable() {
        enterpriseTableModel.setRowCount(0); // Clear existing rows
        for (Enterprise enterprise : enterprises) {
            enterpriseTableModel.addRow(new Object[]{enterprise.getType()});
        }
    }

    private void updateOrganizationTable(Enterprise selectedEnterprise) {
        organizationTableModel.setRowCount(0); // Clear the table
        for (Organization org : selectedEnterprise.getOrglist()) {
            organizationTableModel.addRow(new Object[]{org.getName()});
        }
    }

}
